Student/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("stud.urls")),
]

stud/urls.py
from django.urls import path
from stud import views

urlpatterns = [
    path("category/",views.CategoryCreateView.as_view(),name='category_add'),
    path("category/<int:pk>/",views.CategoryDetailView.as_view(),name='category-detail'),
    path("student/add",views.StudentCreateView.as_view(),name='student-add'),
    path("student/all",views.StudentListView.as_view(),name='student-list'),
    path("student/<int:pk>/change",views.StudentUpdateView.as_view(),name='student-update'),
     path("student/<int:pk>/remove",views.remove_student,name='remove-student'),
    path("student/<int:pk>/change/list",views.StudentDetailView.as_view(),name='student-detail'),
]

stud/models.py
from django.db import models


class Category(models.Model):
    category_name=models.CharField(max_length=200)

    def __str__(self):
        return self.category_name
    

class Student(models.Model):
    student_name=models.CharField(max_length=200,unique=True)
    place=models.CharField(max_length=200)
    Mobile_number=models.CharField(max_length=200)
    category_name=models.ForeignKey(Category,on_delete=models.CASCADE)

stud/forms.py
from django import forms
from stud.models import Category,Student


class CategoryCreateForm(forms.ModelForm):

    class Meta:
        model=Category
        fields="__all__"


class StudentCreateForm(forms.ModelForm):

    class Meta:
        model=Student
        fields="__all__"

        widgets={

            "student_name":forms.TextInput(attrs={"class":"form-control"}),
             "place":forms.TextInput(attrs={"class":"form-control"}), 
             "Mobile_number":forms.TextInput(attrs={"class":"form-control"})
        }



class StudentChangeForm(forms.ModelForm):

    class Meta:
        model=Student
        fields="__all__"

        widgets={

            "student_name":forms.TextInput(attrs={"class":"form-control"}),
             "place":forms.TextInput(attrs={"class":"form-control"}), 
             "Mobile_number":forms.TextInput(attrs={"class":"form-control"})
        }




# class CategorySearchForm(forms.Form):
#     category_name=forms.CharField()

stud/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render,redirect
from stud.forms import CategoryCreateForm,StudentCreateForm,StudentChangeForm
from stud.models import Category,Student
from django.views.generic import View,CreateView,ListView,UpdateView,DetailView
from django.urls import reverse_lazy

class CategoryCreateView(CreateView,ListView):
    template_name="category_add.html"
    form_class= CategoryCreateForm
    model=Category
    context_object_name="categories"
    success_url=reverse_lazy("category_add")

class CategoryDetailView(DetailView):
    template_name="category_detail.html"
    context_object_name="categories"
    model=Category
   

    


class StudentCreateView(View):
   def get(self,request,*args,**kwargs):
        form=StudentCreateForm()
        return render(request,"student_add.html",{"form":form})
    
   def post(self,request,*args, **kwargs):
        form=StudentCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("student-add")
        else:
             return render(request,"student_add.html",{"form":form})
        

class StudentListView(ListView):
   
    template_name="stud_list.html"
    model=Student
    context_object_name="stud"



class StudentUpdateView(UpdateView):
   
    template_name="stud_update.html"
    success_url=reverse_lazy("student-list")
    form_class=StudentChangeForm
    model=Student

class StudentDetailView(DetailView):
    template_name="studentdetail.html"
    model=Student
    context_object_name="s"
    

def remove_student(request,*args,**kwargs):
    id=kwargs.get("pk")
    Student.objects.get(id=id).delete()
    return redirect("student-list")




   

    
  
        


    
    








 

    



   

stud/templates/category_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>


<div class="container d-flex flex-column align-items-center mt-5">
    <div class="border border-4 p-5">
     <h1 class="text-center mb-3">Categories</h1>
     <div class="w-100">
      <form action="" method="post">
  
          {%csrf_token%}
          {{form.as_p}}
          <button type="submit" class="btn btn-success form-control">Add</button>
      </form>
  
     </div>
  
     <div class="mt-5 w-100">
      <table class="table table-striped">
          <tr>
              <td>Name</td>
              <td>Action</td>
          </tr>
          {%for cat in categories%}
             <tr>
              <td>{{cat.category_name}}</td>
              <td>
                  <a href="{%url 'category-detail' cat.id%}">view</a>
              </td>
      
             </tr>
          {%endfor%}
      
      </table>
     </div>
  
    </div>
 
 
 </div>

     
</body>
</html>

stud/templates/category_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>stud</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"> 
    <script src="https://kit.fontawesome.com/c74c679b1d.js" crossorigin="anonymous"></script>


</head>
<body>
<div class="container">
    <div class="row mt-5 ">
        <h2 class="text-center mb-3">Listing all Students</h2>
        <div class="col-1"></div>
        <div class="col-10 ">
            <table class="table table-striped table-hover  border border-3 border shadow">
                <tr class="table table-info border border-dark">
                    <td>Name</td>
                    <td>place</td>
                    <td>Mobilenumber</td>
                    <td>Category</td>
                   
                    </tr>
               
                    {%for c in categories.student_set.all%}
                    <tr>
                      <td>{{c.student_name}}</td> 
                      <td>{{c.place}}</td>
                      <td>{{c.Mobile_number}}</td>
                      <td>{{c.category_name}}</td>
                    

                    </tr>
                    {%endfor%}
               
                    </table>
                   
                    </div>
                    </div>
                    </div>
                    </body>
                    </html>
                    
                

stud/templates/categorylist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
<table class="table table-striped table-hover  border border-3 border shadow">
    <tr class="table table-info border border-dark">
        <td>Name</td>
        <td>Action</td>
        </tr>
        {%for c in cat%}
        <tr>
        <td>{{c.category_name}}</td>
         <td>
            <a href="{% url 'category-detail' c.id %}">View</a>
            
        </td>


        </tr>
       
         {%endfor%}
        </table>
</body>
</html>

stud/templates/stud_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>stud</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"> 
    <script src="https://kit.fontawesome.com/c74c679b1d.js" crossorigin="anonymous"></script>


</head>
<body>
<div class="container">
    <div class="row mt-5 ">
        <h2 class="text-center mb-3">Listing all Students</h2>
        <div class="col-1"></div>
        <div class="col-10 ">
            <table class="table table-striped table-hover  border border-3 border shadow">
                <tr class="table table-info border border-dark">
                    <td>Name</td>
                    <td>place</td>
                    <td>Mobilenumber</td>
                    <td>Category</td>
                    <td>Action</td>
                    </tr>

                    {%for s in stud%}
                    <tr>
                    <td>{{s.student_name}}</td>
                    <td>{{s.place}}</td>
                    <td>{{s.Mobile_number}}</td>
                    <td>{{s.category_name}}</td>
                     <td><a href="{% url 'student-update' s.id %}">edit</a>
                        <a href="{% url 'remove-student' s.id %}">delete</a>
                        <a href="{% url 'student-detail' s.id %}">View</a>
                        
                    </td>


                    </tr>
                    {%endfor%}
                    </table>
                   
                    </div>
                    </div>
                    </div>
                    </body>
                    </html>
                    
                

stud/templates/stud_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student add</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <div class="container mt-5">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6 shadow p-3">
                <form action="" method="post">
                {%csrf_token%}
                {{form.as_p}}
                <button type="submit" class="btn btn-outline-success form-control">Add</button>
            </form>
            </div>
            <div class="col-3"></div>
        </div>
    </div>
    
</body>
</html>

stud/templates/student_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student add</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <div class="container mt-5">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6 shadow p-3">
                <form action="" method="post">
                {%csrf_token%}
                {{form.as_p}}
                <button type="submit" class="btn btn-outline-success form-control">Add</button>
            </form>
            </div>
            <div class="col-3"></div>
        </div>
    </div>
    
</body>
</html>

stud/templates/studentdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>olx</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"> 
    <script src="https://kit.fontawesome.com/c74c679b1d.js" crossorigin="anonymous"></script>


</head>
<body>
<div class="container">
    <div class="row mt-5 ">
        <h2 class="text-center mb-3">Listing all Students</h2>
        <div class="col-1"></div>
        <div class="col-10 ">
            <table class="table table-striped table-hover  border border-3 border shadow">
                <tr class="table table-info border border-dark">
                    <td>Name</td>
                    <td>place</td>
                    <td>Mobilenumber</td>
                    <td>Category</td>
                    <td>Action</td>
                    </tr>

                    <tr>
                    <td>{{s.student_name}}</td>
                    <td>{{s.place}}</td>
                    <td>{{s.Mobile_number}}</td>
                    <td>{{s.category_name}}</td>


                    </tr>
                   
                    </table>
                   
                    </div>
                    </div>
                    </div>
                    </body>
                    </html>
                    
                

stud/templates/studentlistBycategory.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <table class="table table-striped table-hover  border border-3 border shadow">
        <tr class="table table-info border border-dark">
            <td>Name</td>
            <td>place</td>
            <td>Mobilenumber</td>
            <td>Category</td>
            <td>Action</td>
            </tr>
            {%for c in cat%}
    
             {%for s in c.student_set.all%}
            <tr>
            <td>{{s.student_name}}</td>
            <td>{{s.place}}</td>
            <td>{{s.Mobile_number}}</td>
            <td>{{s.category_name}}</td>
             <td><a href="{% url 'student-update' s.id %}">edit</a>
                <a href="{% url 'remove-student' s.id %}">delete</a>
                <a href="{% url 'student-detail' s.id %}">View</a>
                
            </td>
    
    
            </tr>
            {%endfor%}
             {%endfor%}
            </table>
</body>
</html>